import type { IconType } from "react-icons";
import {
  SiPython,
  SiJavascript,
  SiPostgresql,
  SiOpenjdk,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiSpringboot,
  SiNestjs,
  SiExpress,
  SiReact,
  SiNextdotjs,
 SiJest,
  SiMongodb,
  SiRedis,
  SiCloudflare,
  SiGit,
  SiGithub,
  SiGitlab,
  SiJira,
  SiDocker,
  SiKubernetes,
  SiArgo,
  SiGithubactions,
  SiApachekafka,
  SiLinux,
  SiApple,
  SiTrello,
  SiAmazonwebservices,
} from "react-icons/si";

/** Map skill slug (from data/skills) to react-icons/si component. Missing entries use generic fallback. */
export const SKILL_ICONS: Record<string, IconType> = {
  python: SiPython,
  javascript: SiJavascript,
  postgresql: SiPostgresql,
  java: SiOpenjdk,
  typescript: SiTypescript,
  html5: SiHtml5,
  css: SiCss3,
  css3: SiCss3,
  springboot: SiSpringboot,
  nestjs: SiNestjs,
  express: SiExpress,
  react: SiReact,
  nextdotjs: SiNextdotjs,
  jest: SiJest,
  mongodb: SiMongodb,
  redis: SiRedis,
  amazonaws: SiAmazonwebservices,
  cloudflare: SiCloudflare,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  jira: SiJira,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  argo: SiArgo,
  githubactions: SiGithubactions,
  apachekafka: SiApachekafka,
  linux: SiLinux,
  apple: SiApple,
  trello: SiTrello,
};
